workflows:
  ios-workflow:
    name: iOS StopwatchApp Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build iOS App
        script: xcodebuild -project StopwatchApp.xcodeproj -scheme StopwatchApp -sdk iphoneos -configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
